import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import "./globals.css";
import ProviderWrapper from "@/components/ProviderWrapper";
import { ToastProvider } from "@/contexts/ToastContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppRouterCacheProvider>
        <ProviderWrapper>
          <ToastProvider>
            <body className={inter.className}>{children}</body>
          </ToastProvider>
        </ProviderWrapper>
      </AppRouterCacheProvider>
    </html>
  );
}
